# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

if [[ -x "${ZDOTDIR:-$HOME}/.pyenv/bin/pyenv" ]] ; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

if [[ -x "/opt/homebrew/bin/pyenv" ]] ; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

if [[ -s "/opt/homebrew/opt/asdf/libexec/asdf.sh" ]]; then
  source "/opt/homebrew/opt/asdf/libexec/asdf.sh"
  # append completions to fpath
  fpath=("/opt/homebrew/opt/asdf/libexec/completions" $fpath)
  # initialise completions with ZSH's compinit
  autoload -Uz compinit && compinit
fi

if [[ -s "${ZDOTDIR:-$HOME}/.asdf/asdf.sh" ]]; then
  source "${ZDOTDIR:-$HOME}/.asdf/asdf.sh"
  # append completions to fpath
  fpath=("${ZDOTDIR:-$HOME}/.asdf/completions" $fpath)
  # initialise completions with ZSH's compinit
  autoload -Uz compinit && compinit
fi

DIRENV_BIN=$(which direnv)

if [[ -x $DIRENV_BIN ]]; then
  eval "$(direnv hook zsh)"
fi


TERRAFORM_BIN=$(which terraform)
if [[ -x $TERRAFORM_BIN ]]; then
  autoload -U +X bashcompinit && bashcompinit
  complete -o nospace -C /opt/homebrew/bin/terraform terraform
fi

